command_timeout = 10_000
## FIRST LINE/ROW: Info & Status
# First param ‚îÄ‚îå
[username]
format = " [‚ï≠‚îÄ$user]($style)"
show_always = true
style_root = "bold red"
style_user = "bold red"

# Second param
[hostname]
disabled = false
format = " <<<[$hostname]($style)>>> [In Directory -->](bold dimmed blue) "
ssh_only = false
style = "bold dimmed red"
trim_at = "-"

# Third param
[directory]
format = "| [($path)]($style) | on [Ôêò master](bold purple) "
style = "purple"

[memory_usage]
format = "<< [${ram}]($style) >> "
threshold = 10
style = "bold dimmed green"
disabled = false

# Fourth param
[sudo]
disabled = true

# Before all the version info (python, nodejs, php, etc.)
[git_branch]
format = "($style) "
symbol = "."
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
ahead = "‚á°${count}"
behind = "‚á£${count}"
deleted = "x"
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}"
style = "white"

# Last param in the first line/row
[cmd_duration]
disabled = false
format = " <-- [This action took](bold dimmed cyan) [$duration]($style)"
min_time = 0
style = "bold dimmed yellow"


## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
charging_symbol = "ÔñÉ"
disabled = true
discharging_symbol = "ÔñÇ"
full_symbol = "Ôï∏"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
disabled = false
style = "bold red"
threshold = 10

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
disabled = true
style = "bold yellow"
threshold = 50

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
disabled = true
style = "bold green"
threshold = 80

# Prompt: optional param 1
[time]
disabled = true
format = " üïô $time($style)\n"
style = "bright-white"
time_format = "%T"

# Prompt: param 2
[character]
error_symbol = " [√ó](bold red)"
success_symbol = " [‚ï∞‚îÄŒª](bold red)"

# SYMBOLS
[status]
disabled = false
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
pipestatus = true
symbol = "‚ï∞‚îÄŒ±"

[aws]
symbol = "ÓåΩ "

[conda]
symbol = "ÔÑå "

[dart]
symbol = "Óûò "

[docker_context]
symbol = "Ôåà "

[elixir]
symbol = "Óâµ "

[elm]
symbol = "Óò¨ "

[golang]
symbol = "Óòß "

[java]
symbol = "Óâñ "

[julia]
symbol = "Óò§ "

[nim]
symbol = "Ôö§ "

[nix_shell]
symbol = "Ôãú "

[nodejs]
symbol = "Óâè "

[package]
symbol = "Ô£ñ "

[perl]
symbol = "Óù© "

[php]
symbol = "Óòà "

[python]
symbol = "ÓòÜ "

[ruby]
symbol = "Óàæ "

[rust]
symbol = "Óû® "

[swift]
symbol = "ÔØ£ "
